export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETECH_INGREDIENT_FAILED = "FETECH_INGREDIENT_FAILED";

export const PURCHASE_BURGER_SUCESS = "PURCHASE_BURGER_SUCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
